services:
  
  postgres:
    image: postgres:16.0
    container_name: postgres_for_short_url
    environment: 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 69

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shortener_app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/app/.env:ro
    entrypoint: ["/app/url-shortener"]
    command: ["postgres"]
volumes:
  postgres_data:
