services:
  postgres:
    image: postgres:16.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-adminadmin}
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_DB: ${DB_NAME:-shorturl}
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-admin} -d ${DB_NAME:-shorturl}"]
      interval: 5s
      timeout: 3s
      retries: 69

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST:-postgres}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:-admin}
      DB_PASSWORD: ${DB_PASSWORD:-adminadmin}
      DB_NAME: ${DB_NAME:-shorturl}
      DB_SSLMODE: ${DB_SSLMODE:-disable}
    ports:
      - "8080:8080"
    entrypoint: ["/app/url-shortener"]
    command: ["postgres"]
volumes:
  postgres_data:
